
services:
  web:
    build: .
    container_name: mon-site-web
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: ma-base-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: labdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
